---
title: "Recommendation Workflow"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Recommendation Workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup-vignette, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
if ( file.exists("not_included/daniel_env.R")) {
  source ("not_included/daniel_env.R")
} else {
  source ("../not_included/daniel_env.R")
}

```

```{r startup}
library(spotifyrecommendations)
slovakia_indie_playlist_id <- "1E8vQ9Bt4bRKWm0NTzSMt2"
slovakia_top_50_playlist_id <- "6WrpeNyqtoq6PEDXyuamGt"
sound_of_dutch_indie_playlist_id <- "2pSeH1YQCSICs2knjs7e5o"

token  <- get_spotify_access_token()
```


```{r listen_local_artists}
data ("listen_local_artists")

listen_local_artists %>%
  dplyr::sample_n(12)
```

The `?get_playlist` information uses `?get_release_country`

```{r get_playlist_information}

slovakia_indie_playlist_info <- get_playlist_information(
  playlist_id  = slovakia_indie_playlist_id, 
  token = token
  )

slovakia_top_50_info <- get_playlist_information(
  playlist_id  = slovakia_top_50_playlist_id, 
  token = token
  )

dutch_indie_info <- get_playlist_information(
  playlist_id  = sound_of_dutch_indie_playlist_id, 
  token = token
  )

slovakia_indie_playlist_info$user_playlist_artists %>% head ()
slovakia_indie_playlist_info$user_playlist_tracks  %>% head ()
```


```{r initial_recommendations}

sk_artist_ids <- get_national_artist_ids("sk")

initial_slovak_indie <- initial_recommendations(
  playlist_information = slovakia_indie_playlist_info, 
  target_ids = sk_artist_ids, 
  token = token )

initial_slovak_hits <- initial_recommendations(
  playlist_information = slovakia_top_50_info, 
  target_ids = sk_artist_ids, 
  token = token )

initial_dutch_indie <- initial_recommendations(
  playlist_information = dutch_indie_info, 
  target_ids = sk_artist_ids, 
  token = token )


```


```{r}
sum(initial_slovak_indie$release_country_code == "sk")
sum(initial_slovak_indie$target_artists)
```



```{r}
sum(initial_slovak_hits$release_country_code == "sk")
sum(initial_slovak_hits$target_artists)
```



```{r}
sum(initial_dutch_indie$release_country_code == "sk")
sum(initial_dutch_indie$target_artists)
```

## Recommendations Based On Artist Similarity

```{r recommend-by-artist}
recommended_by_artist_similarity <- get_local_artist_recommendations(
  user_playlist_artists = dutch_indie_info, 
  n = 5
  )
```

## Recommendations Based On Genre

```{r recommend-by-genre}

dutch_artists_by_genre <- get_artist_genre(
  user_playlist_artists = dutch_indie_info$user_playlist_artists
  )

recommended_by_genre <- get_artist_recommendations_genre(
  artists_by_genre = dutch_artists_by_genre , 
  target_nationality = "sk"
  )
```


## Track Recommendatinos

```{r}
vars_to_select <- c( "id", "name", "popularity", 
                    "uri", "external_ids.isrc",
                    "release_country_code", 
                    "target_artists")
initial_dutch_indie
 target_ids = get_national_artist_ids("sk")

further_ducth_indie <- get_track_recommendations_artist (
  spotify_artist_id = c(
    recommended_by_artist_similarity, recommended_by_genre
    ), 
  target_nationality = "sk", 
  target_release = NULL, 
  authorization = token
)

recommendations_for_dutch_indie <- initial_dutch_indie %>%
  select ( all_of(vars_to_select) ) %>% 
  bind_rows ( further_ducth_indie  %>%
                select (all_of(vars_to_select))
              )
```
```{r}
start_time <- Sys.time()
slovak_indie_based <- get_local_recommendations(
  user_playlist_id = "1E8vQ9Bt4bRKWm0NTzSMt2",
  recommendation_type = "release"
)
Sys.time()-start_time
```


```{r}
start_time <- Sys.time()
global_top_50 <- get_local_recommendations(
  user_playlist_id = "1KNl4AYfgZtOVm9KHkhPTF",
)
Sys.time()-start_time
```


```{r}
start_time <- Sys.time()
french_post_rock <- get_local_recommendations(
  user_playlist_id = "66GxbkUX9OZikMgn338pz6", 
  authorization = token 
)
Sys.time()-start_time
```

```{r}
start_time <- Sys.time()
french_rock <- get_local_recommendations(
    user_playlist_id = "6uL4zN0tryTmOsrhcknaIS"
)
Sys.time()-start_time
```


```{r}
start_time <- Sys.time()
french_rock <- get_local_recommendations(
    user_playlist_id = "0qJTEzbjENk61TtYeqFxfq"
)
Sys.time()-start_time
```
